// Generates worker/assets.generated.js from the real CSS and client script.
//
// The Node entry point reads these off disk at boot, but a Worker has no
// filesystem, so for deploys they are baked into a module. JSON.stringify does
// the escaping, so nothing in the CSS or JS can break the generated file.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const css = readFileSync(join(root, 'src/ui/app.css'), 'utf8');
const js = readFileSync(join(root, 'src/ui/app.js'), 'utf8');

mkdirSync(join(root, 'worker'), { recursive: true });
writeFileSync(
  join(root, 'worker/assets.generated.js'),
  '// GENERATED by scripts/build-assets.mjs — do not edit.\n'
  + '// Source of truth is src/ui/app.css and src/ui/app.js.\n'
  + `export const CSS = ${JSON.stringify(css)};\n`
  + `export const JS = ${JSON.stringify(js)};\n`,
);

console.log(`assets baked: css ${(css.length / 1024).toFixed(1)}kB, js ${(js.length / 1024).toFixed(1)}kB`);
